title: "ELEANOR Travel"
subtitle: "Voyages élégants & expériences sur mesure"
description: "Agence de voyages haut de gamme basée à Le Kef, offrant des prestations personnalisées en Tunisie et à l’international."
url: "https://ton-nom-utilisateur.github.io"
baseurl: "" # Laisser vide si ton site est à la racine du dépôt
locale: "fr"

# Thème Minimal Mistakes
remote_theme: mmistakes/minimal-mistakes

# Logo et favicon
logo: "/assets/images/logo.png"
favicon: "/assets/images/favicon.ico"

# Auteur
author:
  name: "ELEANOR Travel"
  avatar: "/assets/images/avatar.jpg"
  bio: "Des voyages qui reflètent votre style et vos rêves."
  location: "Le Kef, Tunisie"

# Réseaux sociaux (à personnaliser)
social:
  - label: "Facebook"
    icon: "fab fa-facebook-f"
    url: "https://facebook.com/TonPage"
  - label: "Instagram"
    icon: "fab fa-instagram"
    url: "https://instagram.com/TonProfil"

# Navigation principale
main:
  - title: "Accueil"
    url: "/"
  - title: "Destinations"
    url: "/destinations/"
  - title: "Services"
    url: "/services/"
  - title: "Contact"
    url: "/contact/"

# Paramètres du thème
theme_settings:
  minimal_mistakes_skin: "default" # Autres choix : air, aqua, contrast...
  comments: false
  analytics: false
